### ISSUE TITLE
Skipped jest tests are shown as failed in testomat reporting

### ISSUE THREAD

**Issue by poliarush** [testomatio/app#76]
![image](https://user-images.githubusercontent.com/325722/83040300-653b7280-a03f-11ea-974c-b8f4e9b9197b.png)

![image](https://user-images.githubusercontent.com/325722/83040329-6e2c4400-a03f-11ea-9aa5-960bce75aaec.png)

**Comment by poliarush** [comment]
execution was done by run command 

```
env TESTOMATIO=wkxf4fbf30lp npx jest -t="It should return correct value"
```

**Comment by koushikmohan1996** [comment]
@poliarush On analysis found 2 problems

1. Skipped tests are marked as `pending` by jest but server can understand `skipped` only
2. In jest if pattern is used all other test are marked as pending. Need to add a check if grep is used or not to publish the test that are actually skipped and not because of grep
