### ISSUE TITLE
Runs section default view is displaying chart with run history wrongly ordered

### ISSUE THREAD

**Issue by RaspFR** [testomatio/app#873]
**Describe the bug**
Runs section default view is displaying chart with run history wrongly ordered

**To Reproduce**
1. Go to runs section and look at the chart

**Expected behavior**
Runs history list should be ordered by date asc. And the chat should reflect this order.

**Screenshots**
![Screenshot 2023-11-15 at 09 17 44](https://github.com/testomatio/app/assets/10197265/c0f30d6e-1ed6-49c3-bcfc-2965394ec0f5)

**Desktop (please complete the following information):**
 - OS: MAC Sonoma 14.0
 - Browser: chrome
 - Browser Version:  119.0.6045.123
 - Application: production

**Comment by littlefrontender** [comment]
![Снимок экрана 2023-12-19 в 12 24 29](https://github.com/testomatio/app/assets/79913874/47d9af45-e807-44e5-b07c-d8aa993a2d36)
Sorting occurs by `updated_at`, but we render `finished_at`.

@poliarush @DavertMik should we change the sorting here?

**Comment by poliarush** [comment]
@littlefrontender 
- when we re-launch a run we need to get it to the top of the list, that's why it's sorted by `updated_at`, and we need to keep this behaviour
- however, when the run is finished it should be sorted properly by `finished at` 

in the case above, finished runs are not sorted correctly by by `finished_at`

**Comment by TetianaKhomenko** [comment]
Hi @RaspFR ! The issue should be fixed in the upcoming release.
