### ISSUE TITLE
One Test Run Send 3 slack notifications with the same report id but different time and amount of pass/failed tests

### ISSUE THREAD

**Issue by denys-iaremenko** [testomatio/app#940]
**Describe the bug**
One Test Run Send 3 slack notifications with the same report id but different time and amount of pass/failed tests.
Tests are running in Jenkins agent on AWS

**To Reproduce**
1. Start Automation run from Jenkins
2. Wait till notifications will be presented in slack

**Expected behavior**
One slack message is send with final result

**Actual behavior**
3 Messages with different data but same report id were send in slack

**Screenshots**
![Screenshot 2024-02-16 at 15 19 58](https://github.com/testomatio/app/assets/84392142/b2d62ca8-1e6c-4d3c-b846-4d096adab410)

**Desktop (please complete the following information):**
 - OS: Linux/Max
 - Browser N/A
 - Application: production

**Comment by TetianaKhomenko** [comment]
Hi @denys-iaremenko! Do you use workers?

**Comment by DavertMik** [comment]
@denys-iaremenko notifications are correct because on all of these 3 conditions run is considered as FINISHED

The question is why run is finished when new tests are coming in.

Seems like Run is incorrectly reported and marked as finished when it is not. Could you share more details on the reporting?


* test framework
* is CI environment or not
* do you use parallel processes or sharding
* run command

**Comment by poliarush** [comment]
@denys-iaremenko please re-check, it should be fixed.
