### ISSUE TITLE
The scenarious outlines examples are not changed after saving

### ISSUE THREAD

**Issue by Tny6918** [testomatio/app#957]
**Describe the bug**

**To Reproduce**
1. Create a test case with Scenario Outline
2. Add Examples and save the test case
3. Open the test case and change Examples with new updated test data
4. Push the button Save and reload the page

**Expected behavior**
new examples are saved and the table shows updated info

**Screenshots**
Video - https://app.screencast.com/6u949A0I5wE3w

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]
 - Browser Version [122.0.6261.112 ]
 - Application: [production]

**Comment by TetianaKhomenko** [comment]
Hi @Tny6918! The issue has been fixed. The fix will be published in the upcoming release.

https://github.com/testomatio/app/assets/77803888/7a19efa9-812b-4e83-b10d-9b07e66387a1

**Comment by TetianaKhomenko** [comment]
Hi @Tny6918! The fix is live now. Could you please check it on your side?

**Comment by Tny6918** [comment]
If your test suit was a part of the saved and used test plan and that test plan was used in test runs then your previous data from the Examples table will return and you have to reopen each test case and save it again
VIdeo: https://app.screencast.com/hXrch3QIKMvWL

**Comment by TetianaKhomenko** [comment]
@Fro0z1k we need to improve this scenario ^

**Comment by Tny6918** [comment]
so basically I have changed the Examples table and I used it before with old data in the tables test plan. Because of that as I assume the old data returned to the tables and I had to change it again manually

**Comment by TetianaKhomenko** [comment]
Hi @Tny6918! We re-checked this issue and it seems to be fixed. Attaching a video below. 

https://github.com/testomatio/app/assets/77803888/e6e3f99d-e6c5-4a8b-a63c-05ef56897b04

Could you please re-check it on your side? Also if the issue is still present, please add a support user (Project > Settings > Users> Extra menu > Invite support user) to this project so we can take a closer look.

![image](https://github.com/testomatio/app/assets/77803888/96ba75b6-09b9-4683-810e-0ae8a4cf2394)
